variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build: 
  stage: build
  script:
    - echo  C:\Users\ra408\Djigitbet\djigitbet-be\djigitbet\gradlew
test:
  stage: test
  script:
     - echo " ./gradlew test "
