stages:
    - build
    - package

buildntest:
    image: gradle:7.4.2-jdk18
    stage: build
    script:
        - echo "the ci pipline works" > test.txt
        - ls
        - cd djigitbet
        - chmod +x gradlew
        - ./gradlew assemble
        - ./gradlew test
        - ./gradlew sonarqube

    artifacts:
        paths:
            - test.txt


