stages:
    - buildntest
    - deploy
    - sonarwithoutdocker


buildntest:
    image: gradle:7.4.2-jdk17
    stage: buildntest
    script:
        - echo "the ci pipline works" > test.txt
        - ls
        - cd djigitbet
        - chmod +x gradlew
        - sed -i -e 's/\r$//' gradlew
        - ./gradlew assemble
        - ./gradlew test
        

    artifacts:
        paths:
            - test.txt




deploy:
    stage: deploy
    script: 
        - ls -l
        - ls - l /
        - ls -l /home/raga70/.shh
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY  raga70@20.203.252.102 "
            cd djigitbet/ && git pull &&
            docker login -u raga70 -p Zzax9js2Erfevvv &&
            docker pull raga70/djigitbetfe:latest &&
            docker-compose down && docker-compose up -d --build"
    
    
    #reserved for  a windows runner
#sonarqube:
#    stage: sonarwithoutdocker
#    script:
#        - cd djigitbet
#        - chmod +x gradlew
#        - ./gradlew assemble
#        - ./gradlew test jacocoTestReport sonarqube
   
