image: docker:stable
variables:
    IMAGE NAME: "gradle:7.4.2-jdk18 "
services:
 -docker: 20.10.12-dind
build image :
    script :
        - docker build -t $CI_REGISTRY/t1788/demos/docker-image-build/$IMAGE_NAME .
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY/t1788/demos/docker-image-build/$IMAGE_NAME
