variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build: 
  stage: build
  script:
    - echo "the pipline works as expected under windows (jdk is not installed over windows so i wont run ./gradlew assemble) "
test:
  stage: test
  script:
     - echo " ./gradlew test "
